spring.application.name=api-rest

spring.datasource.url=jdbc:mysql://localhost/forohub
spring.datasource.username=root
spring.datasource.password=Basement83#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=emmanuel
spring.security.user.password=1234

jwt.secret=MiClaveSecreta123456
jwt.expiration=3600000  

spring.flyway.enabled=true

